### ISSUE TITLE
<select> tags end up with text and background same color

### ISSUE THREAD

**Issue by typedrat** [catppuccin/zen-browser#37]
I can't get a screenshot easily because opening my screenshot tool closes the select element, but standard HTML dropdowns are unusable right now because they end up with the same color for the text and the background.

**Comment by Jinra** [comment]
try adding this at the bottom of your userChrome.css (before the last curly brace)

```#contentAreaContextMenu menu, menuitem, menupopup {
  color: #c6d0f5 !important;
  }```

**Comment by dragove** [comment]
For better experience, maybe add these can help. based on [Jinra](https://github.com/Jinra)'s config

```css
  #contentAreaContextMenu menu, menuitem, menupopup {
    color: #c6d0f5 !important;
  }
  menupopup > menuitem:hover:not([disabled]) {
    background-color: #51576d !important;
  }
  menupopup > menuitem[_moz-menuactive="true"] {
      background-color: #51576d !important;
  }
  menupopup > menuitem[selected="true"] {
    background-color: #626880 !important;
  }
```
